// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  profileSidebar: [
    {
      type: 'doc',
      label: 'My Profile',
      id: 'About-me',
    },
  ],

  projectSidebar: [
    {
      type: 'doc',
      label: 'Overview',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Documentation Tooling',
      link: {
        type: 'doc',
        id: 'documentation-tooling/intro'
      },
      items: [
        {
      type: 'category',
      label: 'Mautic',
      link: {
        type: 'doc',
        id: 'documentation-tooling/mautic-overview'
      },
      items: [
        'documentation-tooling/getting-started',
        {
          type: 'category',
          label: 'API Reference',
          items: [
            'documentation-tooling/reference/get-contact',
            'documentation-tooling/reference/create-campaign',
          ],
        }
      ],
    },
      ]
    }, 

    {
      type: 'category',
      label: 'API Documentation and Open API',
      link: {
        type: 'doc',
        id: 'api-documentation/intro'
      },
      items: [
        {
      type: 'category',
      label: 'Chimoney',
      link: {
        type: 'doc',
        id: 'api-documentation/chimoney-overview'
      },
      items: [
        'api-documentation/getting-started',
        {
          type: 'category',
          label: 'API Reference',
          items: [
            'api-documentation/reference/get-transaction',
            'api-documentation/reference/post-transaction',
          ],
        }
      ],
    },

      ]
    },

  ],
};


export default sidebars;
