name: Practice Workflow

on:
  push:
    branches:
      - portfolio
  workflow_dispatch:

jobs:
  practice-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print GitHub username and repo details
        run: echo "Username: ${{ github.actor }}, Repository: ${{ github.repository }}"

      - name: Install Vale
        run: |
          brew install vale

      - name: Verify Vale installation
        run: |
          vale --version
          echo "Vale was installed on my machine."
