name: Print GitHub Info

on: 
  push:   # Runs whenever you push
  workflow_dispatch:  # Also allows you to run it manually

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print GitHub username and Repo details
        run: |
          echo "GitHub Username: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"

      - name: Print Vale installation confirmation
        run: |
          echo "Vale was installed on my machine."
