name: reviewdog
on: [pull_request]

jobs:
  review:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Code
         uses: actions/checkout@v4

       - name: Run Vale Check
         uses: errata-ai/vale-action@v2.1.1